#!/usr/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
sh ~/.config/polybar/launch.sh

# Notifications
killall dunst
dunst --config ~/.config/dunst/dunstrconf &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
feh --bg-fill -r -z ~/Pictures/Wallpaper

# Dex
dex -as /etc/xdg/autostart:~/.config/autostart

# Picom
picom --config ~/.config/picom/picom.conf &

# Udiskie
udiskie --appindicator &

# Networkd notify
networkd-notify &

# General configuration
conf() {
  bspc config "$@" &
}

rule() {
  bspc rule -a "$@" &
}

bspc monitor -d I II III IV V VI VII

conf border_width 0
conf window_gap 0

conf focused_border_color "#7373ff"
conf normal_border_color "#1e0f2c"
conf active_border_color "#230b52"
conf presel_feedback_color "#4c566a"

conf split_ratio 0.50
conf borderless_monocle true
conf gapless_monocle true
conf pointer_follows_focus true
conf focus_follows_pointer true
conf single_monocle true
conf initial_polarity first_child
conf pointer_action2 resize_corner

rule goneovim desktop='^1'
rule firefox desktop='^2'
rule chromium desktop='^2'
rule discord desktop='^3'
rule Screenkey manage=off

{ pkill -x borders; { sleep 0.1; borders & } } &
