#!/usr/bin/sh

# XDG based directory specifications settings
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
export XDG_STATE_HOME=${XDG_STATE_HOME:-~/.local/state}
export XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}

[ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ] && . "$XDG_CONFIG_HOME/user-dirs.dirs"

export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export ANDROID_AVD_HOME="$XDG_DATA_HOME/android"
export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME/android"
export ADB_VENDOR_KEY="$XDG_CONFIG_HOME/android"
export ACKRC="$XDG_CONFIG_HOME/ack/ackrc"
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME="$XDG_CONFIG_HOME/tool-versions"
export ASDF_DIR="$XDG_DATA_HOME/asdf"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf-data"
export ASDF_NPM_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/default-npm-packages"
export ASPELL_CONF="per-conf $XDG_CONFIG_HOME/aspell/en.prepl"
export ATOM_HOME="$XDG_DATA_HOME/atom"
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"
export AZURE_CONFIG_DIR="$XDG_DATA_HOME/azure"
export BABEL_CACHE_PATH="$XDG_CACHE_HOME/babel/babel.json"
export BASH_COMPLETION_USER_FILE="$XDG_CONFIG_HOME/bash/bash_completion"
export BUN_INSTALL="$XDG_DATA_HOME/bun"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle/plugin"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export ELM_HOME="$XDG_CONFIG_HOME/elm"
export GOPATH="$XDG_DATA_HOME/go"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export IPFS_PATH="$XDG_DATA_HOME/ipfs"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export KDEHOME="$XDG_CONFIG_HOME/kde"
export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker/machine"
export MATHEMATICA_USERBASE="$XDG_CONFIG_HOME/Mathematica"
export MINIKUBE_HOME="$XDG_DATA_HOME/minikube"
export MOST_INITFILE="$XDG_CONFIG_HOME/mostrc"
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
export MYSQL_HISTFILE="$XDG_STATE_HOME/mysql_history"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/config"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export npm_config_devdir="$XDG_CACHE_HOME/npm"
export npm_config_cache="$XDG_CACHE_HOME/npm"
export npm_config_prefix="$XDG_DATA_HOME/npm"
export npm_config_tmp="$XDG_RUNTIME_DIR/npm"
export npm_config_init_module="$XDG_CONFIG_HOME/npm/config/npm-init.js"
export NUGET_PACKAGES="$XDG_CACHE_HOME/nuget/packages"
export NVM_DIR="$XDG_DATA_HOME/nvm"
export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
export PERL5LIB="$XDG_DATA_HOME/perl:$PERL5LIB"
export PERL_CPANM_OPT="--local-lib=$XDG_DATA_HOME/perl"
export PROXYCHAINS_CONF_FILE="$XDG_CONFIG_HOME/proxychains/proxychains.conf"
export PSQLRC="$XDG_CONFIG_HOME/postgres/rc"
export PSQL_HISTORY="$XDG_STATE_HOME/postgres/history"
export PGPASSFILE="$XDG_CONFIG_HOME/postgres/pass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/postgres/service.conf"
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
export PYTHON_EGG_CACHE="$XDG_CACHE_HOME/python-eggs"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/startup.py"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export PULSE_COOKIE="$XDG_STATE_HOME/pulse/cookie"
export REDISCLI_HISTFILE="$XDG_STATE_HOME/redis/history"
export REDISCLI_RCFILE="$XDG_CONFIG_HOME/redis/redisclirc"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite/history"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR/tmux"
export UNCRUSTIFY_CONFIG="$XDG_CONFIG_HOME/uncrustify/uncrustify.cfg"
export VAGRANT_HOME="$XDG_DATA_HOME/vagrant"
export VAGRANT_ALIAS_FILE="$XDG_DATA_HOME/vagrant/aliases"
export WAKATIME_HOME="$XDG_CONFIG_HOME/wakatime"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
export WINEPREFIXES="$XDG_DATA_HOME/wineprefixes"
export WINEPREFIX="$WINEPREFIXES/default"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export WORKON_HOME="$XDG_DATA_HOME/virtualenvs"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java -Dawt.useSystemAAFontSettings=gasp -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=gasp"
export __GL_SHADER_DISK_CACHE_PATH="$XDG_DATA_HOME/nvidia"

# Create directories
mkdir -p "$XDG_STATE_HOME/fzf" # Used internally
mkdir -p "$XDG_DATA_HOME/gnupg"
chmod 700 "$XDG_DATA_HOME/gnupg"
mkdir -p "$XDG_CONFIG_HOME/postgres"
mkdir -p "$XDG_STATE_HOME/pulse"
mkdir -p "$XDG_DATA_HOME/wineprefixes"
mkdir -p "$XDG_STATE_HOME/wget"
mkdir -p "$XDG_STATE_HOME/less"
mkdir -p "$XDG_STATE_HOME/sqlite"
mkdir -p "$XDG_CONFIG_HOME/wakatime"
